// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetScanProgress() {
  return window['go']['scanner']['App']['GetScanProgress']();
}

export function GetScanStatus() {
  return window['go']['scanner']['App']['GetScanStatus']();
}

export function ScanPorts(arg1, arg2, arg3, arg4) {
  return window['go']['scanner']['App']['ScanPorts'](arg1, arg2, arg3, arg4);
}

export function Startup(arg1) {
  return window['go']['scanner']['App']['Startup'](arg1);
}

export function StopScan() {
  return window['go']['scanner']['App']['StopScan']();
}
