// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {gitdorker} from '../models';
import {context} from '../models';

export function Gitdorker(arg1:string,arg2:string,arg3:string):Promise<gitdorker.GithubResult>;

export function GitdorkerCalculate(arg1:number,arg2:number):Promise<number>;

export function Startup(arg1:context.Context):Promise<void>;
