// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Gitdorker(arg1, arg2) {
  return window['go']['gitdorker']['GitdorkerService']['Gitdorker'](arg1, arg2);
}
