// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Jsfinder(arg1, arg2) {
  return window['go']['jsfinder']['App']['Jsfinder'](arg1, arg2);
}

export function Startup(arg1) {
  return window['go']['jsfinder']['App']['Startup'](arg1);
}
