// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ScanPorts(arg1) {
  return window['go']['main']['App']['ScanPorts'](arg1);
}
