// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetDirsearchProgress() {
  return window['go']['main']['App']['GetDirsearchProgress']();
}

export function GetDirsearchStatus() {
  return window['go']['main']['App']['GetDirsearchStatus']();
}

export function GetScanProgress() {
  return window['go']['main']['App']['GetScanProgress']();
}

export function GetScanStatus() {
  return window['go']['main']['App']['GetScanStatus']();
}

export function ScanPorts(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['ScanPorts'](arg1, arg2, arg3, arg4);
}

export function StartDirsearch(arg1, arg2, arg3) {
  return window['go']['main']['App']['StartDirsearch'](arg1, arg2, arg3);
}

export function StopDirsearch() {
  return window['go']['main']['App']['StopDirsearch']();
}

export function StopScan() {
  return window['go']['main']['App']['StopScan']();
}
