// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {context} from '../models';

export function OpenFileDialog():Promise<string>;

export function StartDirsearch(arg1:string,arg2:string,arg3:number):Promise<void>;

export function Startup(arg1:context.Context):Promise<void>;

export function StopDirsearch():Promise<void>;
