// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function OpenFileDialog() {
  return window['go']['dirsearch']['App']['OpenFileDialog']();
}

export function StartDirsearch(arg1, arg2, arg3) {
  return window['go']['dirsearch']['App']['StartDirsearch'](arg1, arg2, arg3);
}

export function Startup(arg1) {
  return window['go']['dirsearch']['App']['Startup'](arg1);
}

export function StopDirsearch() {
  return window['go']['dirsearch']['App']['StopDirsearch']();
}
